### ISSUE TITLE
Add commit scope

### ISSUE THREAD

**Issue by alirezanqp** [ali-hv/comsu#5]
I think that in commits, the scope of that commit should also be added, because later it is easier to track the scope of the change.

example:

feat(scope): message
feat(product): send an email to the customer

can also add commit description, which we can discuss in another issue.

**Comment by ali-hv** [comment]
Hi dear alireza, as i mentioned in README, you can change the prompt to anything you want and generate your own custom commit messages, but yes it can have some flags for that, like if user runs the 'git comsu' command with -d flag, it use a prompt that adds description to commit message, or when run with -s, it uses the prompt that adds scope to commit message. I will add these stuff in future when i find some free time in my day. And of course i will be so happy if you do it and make a pull request. Thanks for the idea.
